CREATE TABLE IF NOT EXISTS `articles` (
  `id` CHAR(26) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `excerpt` VARCHAR(500) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `category_id` CHAR(26) NULL DEFAULT NULL,
  `cover_image_id` CHAR(26) NULL DEFAULT NULL,
  `status` ENUM('draft','published') NOT NULL DEFAULT 'draft',
  `published_at` TIMESTAMP NULL DEFAULT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `view_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `display_order` INT NOT NULL DEFAULT 0,
  `seo_title` VARCHAR(255) NULL DEFAULT NULL,
  `seo_description` VARCHAR(500) NULL DEFAULT NULL,
  `og_image_id` CHAR(26) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` CHAR(26) NULL DEFAULT NULL,
  `updated_by` CHAR(26) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_articles_slug` (`slug`),
  KEY `IDX_articles_category_id` (`category_id`),
  KEY `IDX_articles_status` (`status`),
  KEY `IDX_articles_is_featured` (`is_featured`),
  KEY `IDX_articles_deleted_at` (`deleted_at`),
  CONSTRAINT `FK_articles_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_articles_cover_image` FOREIGN KEY (`cover_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_articles_og_image` FOREIGN KEY (`og_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
