CREATE TABLE IF NOT EXISTS `consultations` (
  `id` CHAR(26) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `project_type` ENUM('residential','commercial','hospitality','renovation','other') NULL DEFAULT NULL,
  `area` VARCHAR(50) NULL DEFAULT NULL,
  `budget_range` VARCHAR(100) NULL DEFAULT NULL,
  `message` TEXT NOT NULL,
  `product_id` CHAR(26) NULL DEFAULT NULL,
  `status` ENUM('new','contacted','scheduled','completed','cancelled') NOT NULL DEFAULT 'new',
  `assigned_to` CHAR(26) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `status_changed_at` TIMESTAMP NULL DEFAULT NULL,
  `status_changed_by` CHAR(26) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `source` VARCHAR(50) NULL DEFAULT NULL,
  `honeypot` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_consultations_status` (`status`),
  KEY `IDX_consultations_product_id` (`product_id`),
  KEY `IDX_consultations_assigned_to` (`assigned_to`),
  KEY `IDX_consultations_deleted_at` (`deleted_at`),
  CONSTRAINT `FK_consultations_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `FK_consultations_assignee` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
