CREATE TABLE IF NOT EXISTS `media` (
  `id` CHAR(26) NOT NULL,
  `original_filename` VARCHAR(255) NOT NULL,
  `mime_type` VARCHAR(50) NOT NULL,
  `file_size` INT UNSIGNED NOT NULL,
  `original_url` VARCHAR(500) NOT NULL,
  `thumbnail_url` VARCHAR(500) NULL DEFAULT NULL,
  `preview_url` VARCHAR(500) NULL DEFAULT NULL,
  `width` INT UNSIGNED NULL DEFAULT NULL,
  `height` INT UNSIGNED NULL DEFAULT NULL,
  `alt_text` VARCHAR(255) NULL DEFAULT NULL,
  `blurhash` VARCHAR(100) NULL DEFAULT NULL,
  `processing_status` ENUM('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
  `processing_error` TEXT NULL DEFAULT NULL,
  `uploaded_by` CHAR(26) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_media_uploaded_by` (`uploaded_by`),
  KEY `IDX_media_processing_status` (`processing_status`),
  KEY `IDX_media_deleted_at` (`deleted_at`),
  CONSTRAINT `FK_media_uploader` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
