CREATE TABLE IF NOT EXISTS `products` (
  `id` CHAR(26) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `category_id` CHAR(26) NULL DEFAULT NULL,
  `material_type` VARCHAR(100) NULL DEFAULT NULL,
  `finish` VARCHAR(100) NULL DEFAULT NULL,
  `dimensions` JSON NULL DEFAULT NULL,
  `price_range` VARCHAR(100) NULL DEFAULT NULL,
  `cover_image_id` CHAR(26) NULL DEFAULT NULL,
  `status` ENUM('draft','published') NOT NULL DEFAULT 'draft',
  `published_at` TIMESTAMP NULL DEFAULT NULL,
  `is_new` TINYINT(1) NOT NULL DEFAULT 0,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `display_order` INT NOT NULL DEFAULT 0,
  `seo_title` VARCHAR(255) NULL DEFAULT NULL,
  `seo_description` VARCHAR(500) NULL DEFAULT NULL,
  `og_image_id` CHAR(26) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` CHAR(26) NULL DEFAULT NULL,
  `updated_by` CHAR(26) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_products_slug` (`slug`),
  KEY `IDX_products_category_id` (`category_id`),
  KEY `IDX_products_status` (`status`),
  KEY `IDX_products_material_type` (`material_type`),
  KEY `IDX_products_deleted_at` (`deleted_at`),
  CONSTRAINT `FK_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_products_cover_image` FOREIGN KEY (`cover_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_products_og_image` FOREIGN KEY (`og_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
