CREATE TABLE IF NOT EXISTS `projects` (
  `id` CHAR(26) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `category_id` CHAR(26) NULL DEFAULT NULL,
  `style` VARCHAR(100) NULL DEFAULT NULL,
  `materials` JSON NULL DEFAULT NULL,
  `area` VARCHAR(50) NULL DEFAULT NULL,
  `duration` VARCHAR(50) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `year_completed` SMALLINT NULL DEFAULT NULL,
  `cover_image_id` CHAR(26) NULL DEFAULT NULL,
  `status` ENUM('draft','published') NOT NULL DEFAULT 'draft',
  `published_at` TIMESTAMP NULL DEFAULT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `view_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `display_order` INT NOT NULL DEFAULT 0,
  `ref_code` VARCHAR(20) NULL DEFAULT NULL,
  `seo_title` VARCHAR(255) NULL DEFAULT NULL,
  `seo_description` VARCHAR(500) NULL DEFAULT NULL,
  `og_image_id` CHAR(26) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` CHAR(26) NULL DEFAULT NULL,
  `updated_by` CHAR(26) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQ_projects_slug` (`slug`),
  KEY `IDX_projects_category_id` (`category_id`),
  KEY `IDX_projects_status` (`status`),
  KEY `IDX_projects_is_featured` (`is_featured`),
  KEY `IDX_projects_deleted_at` (`deleted_at`),
  KEY `IDX_projects_display_order` (`display_order`),
  CONSTRAINT `FK_projects_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_projects_cover_image` FOREIGN KEY (`cover_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_projects_og_image` FOREIGN KEY (`og_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
