/**
 * Seed 60 bai noi dung cho VietNet Interior
 * Chay trong Docker container: node /app/seed-runner.js
 */
const http = require('http');

const API = 'http://localhost:4000/api';
let TOKEN = '';

function req(method, path, body) {
  return new Promise((resolve, reject) => {
    const url = new URL(API + path);
    const data = body ? JSON.stringify(body) : null;
    const opts = {
      hostname: url.hostname, port: url.port, path: url.pathname + url.search,
      method, headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${TOKEN}` }
    };
    if (data) opts.headers['Content-Length'] = Buffer.byteLength(data);
    const r = http.request(opts, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try { resolve({ status: res.statusCode, body: JSON.parse(d) }); }
        catch { resolve({ status: res.statusCode, body: d }); }
      });
    });
    r.on('error', reject);
    if (data) r.write(data);
    r.end();
  });
}

function mkContent(paragraphs) {
  return JSON.stringify({
    type: 'doc',
    content: paragraphs.map(text => ({ type: 'paragraph', content: [{ type: 'text', text }] }))
  });
}

// ─── DATA ─────────────────────────────────────────────

const CATS = {};

const PROJECTS = [
  {t:'Căn hộ Vinhomes Grand Park 85m²',c:'Căn hộ',s:'Scandinavian',a:'85m²',l:'TP. Thủ Đức, HCM',y:2025,f:true,d:'Căn hộ 3PN Scandinavian hiện đại, tối ưu ánh sáng tự nhiên.',ps:['Dự án căn hộ Vinhomes Grand Park 85m² là công trình tiêu biểu của VietNet Interior năm 2025. Với 3 phòng ngủ, chúng tôi tối ưu hóa từng mét vuông tạo không gian sống thoáng đãng cho gia đình trẻ hiện đại. Phong cách Scandinavian với tông trắng kem chủ đạo kết hợp gỗ sồi tự nhiên.','Ánh sáng tự nhiên được tối ưu nhờ cửa kính lớn và bố trí nội thất thông minh. Phòng khách liên thông bếp và phòng ăn tạo cảm giác rộng rãi. Hệ thống tủ âm tường thiết kế riêng giúp tối ưu không gian lưu trữ mà không làm chật căn phòng.','Mỗi phòng ngủ có bảng màu riêng nhưng đồng nhất tổng thể Scandinavian thanh lịch. Vật liệu sử dụng gồm gỗ sồi Châu Âu, đá thạch anh nhân tạo cho bếp, và đèn LED âm trần tiết kiệm năng lượng. Tổng chi phí 450 triệu đồng, bàn giao trong 45 ngày làm việc.']},
  {t:'Penthouse Midtown Phú Mỹ Hưng 200m²',c:'Căn hộ',s:'Contemporary Luxury',a:'200m²',l:'Quận 7, HCM',y:2025,f:true,d:'Penthouse sang trọng panorama sông Sài Gòn.',ps:['Penthouse Midtown 200m² là dự án cao cấp nhất của VietNet Interior năm 2025. Tầm nhìn panorama ra sông Sài Gòn và skyline thành phố. Contemporary Luxury thể hiện qua đá marble Calacatta nhập Ý, đèn chùm Swarovski, nội thất bespoke đóng riêng.','Phòng khách double-height 5.4m với kính floor-to-ceiling tạo khung cảnh ấn tượng. Bếp mở với đảo marble và thiết bị Gaggenau nhập Đức. Master bedroom 40m² có walk-in closet và spa bathroom với bồn tắm Villeroy & Boch freestanding.','Bảng màu xám than, vàng đồng và trắng ngà — sang trọng nhưng kiềm chế. Tổng giá trị nội thất 3.2 tỷ đồng. Dự án đạt giải Best Interior Design tại Vietnam Property Awards 2025.']},
  {t:'Biệt thự Lucasta Khang Điền 350m²',c:'Biệt thự',s:'Indochine',a:'350m²',l:'Quận 9, HCM',y:2024,f:true,d:'Biệt thự Indochine đương đại cho gia đình 3 thế hệ.',ps:['Biệt thự Lucasta là niềm tự hào của VietNet Interior — kiến trúc Đông Dương truyền thống hòa quyện tiện nghi hiện đại. Công trình 3 tầng 350m² thiết kế cho gia đình 3 thế hệ. Cửa vòm, gạch bông, đèn lồng, gỗ óc chó kết hợp mây tre đan.','Tầng 1: phòng khách trần cao 4m, phòng ăn formal và bếp riêng. Tầng 2: 3 phòng ngủ và phòng thờ trang nghiêm. Tầng 3: phòng chiếu phim mini và sân thượng vườn xanh mát. Cầu thang gỗ óc chó xoắn ốc là focal point toàn bộ ngôi nhà.','Hoàn thành trong 4 tháng thi công, sử dụng hoàn toàn gỗ óc chó Mỹ nhập khẩu và đá granite tự nhiên. Bảng màu xanh rêu đậm, nâu gỗ và trắng ngà. Tổng giá trị nội thất 2.8 tỷ đồng.']},
  {t:'Villa Nghỉ Dưỡng Hồ Tràm 280m²',c:'Biệt thự',s:'Tropical Modern',a:'280m²',l:'Hồ Tràm, BR-VT',y:2024,f:false,d:'Villa biển Tropical Modern hòa mình vào thiên nhiên.',ps:['Villa Hồ Tràm là dự án nghỉ dưỡng đặc biệt — kiến trúc hòa mình vào thiên nhiên biển. Concept Tropical Modern tận dụng không gian mở, ánh sáng tự nhiên và gió biển. Vật liệu chủ đạo gỗ teak, mây tre đan, đá cuội và bê tông trần.','Phòng khách mở hoàn toàn ra bể bơi vô cực qua cửa kính trượt 6m. Phòng tắm master semi-outdoor với vòi sen mưa dưới mái lá. Bếp ngoài trời với lò nướng BBQ phục vụ tiệc biển lãng mạn.','Hoàn thành 3 tháng, tổng chi phí 1.5 tỷ đồng. Hiện villa được cho thuê nghỉ dưỡng qua Airbnb với rating 4.9/5 sao, thu hồi vốn sau 3 năm.']},
  {t:'Văn Phòng FPT Software 500m²',c:'Văn phòng',s:'Modern Industrial',a:'500m²',l:'Quận 1, HCM',y:2025,f:true,d:'Creative Hub cho 200+ nhân viên công nghệ.',ps:['Văn phòng FPT Software tại Quận 1 theo concept Creative Hub — truyền cảm hứng sáng tạo cho hơn 200 nhân viên. Modern Industrial với trần exposed bê tông, hệ thống ống đồng lộ thiên sắp xếp nghệ thuật. Tường gạch thô kết hợp panel gỗ tái chế.','4 zone chức năng: Open workspace với bàn ngồi-đứng điều chỉnh, Phone booths cách âm cho cuộc gọi riêng, Meeting rooms kính cường lực 4 kích cỡ, và Creative lounge với bean bags và bảng brainstorm cho ideation sessions.','Pantry bar phong cách café với máy pha cà phê chuyên nghiệp, vườn cây xanh indoor tưới tự động. Tổng chi phí 1.8 tỷ đồng, hoàn thành trong 60 ngày. Nhân viên FPT đánh giá mức hài lòng 9.2/10.']},
  {t:'Co-working The Hive Thảo Điền 320m²',c:'Văn phòng',s:'Industrial Chic',a:'320m²',l:'Quận 2, HCM',y:2025,f:false,d:'Co-working cao cấp với vertical garden.',ps:['The Hive Thảo Điền là không gian co-working cao cấp dành cho freelancer và startup. Triết lý thiết kế "Work where you feel alive". Industrial Chic với trần exposed, ống đồng lộ, vertical garden 12m² trải từ tầng 1 lên tầng lửng.','Hot desk, dedicated desk, private office từ 2-8 người. Podcast studio cách âm chuyên nghiệp, event space 50 người cho workshop và networking. Wifi 1Gbps với backup line đảm bảo kết nối liên tục suốt ngày.','Kính lớn đón ánh sáng tự nhiên suốt ngày, giảm 60% chi phí điện chiếu sáng. Chi phí thiết kế thi công 950 triệu đồng. Tỷ lệ lấp đầy 95% sau 2 tháng vận hành — chứng minh thiết kế tốt tạo ra giá trị kinh doanh.']},
  {t:'Nhà Hàng Maison de Saigon 180m²',c:'Nhà hàng & Khách sạn',s:'French-Vietnamese',a:'180m²',l:'Quận 1, HCM',y:2024,f:true,d:'Fine-dining French-Vietnamese fusion tại trung tâm Sài Gòn.',ps:['Maison de Saigon là nhà hàng fine-dining kết hợp ẩm thực Pháp-Việt tại Quận 1. Nội thất cổ điển Pháp pha trộn chi tiết Đông Dương: đèn chùm pha lê, ghế velvet xanh navy, bàn gỗ mahogany, gạch bông hoa văn truyền thống.','Chia 3 không gian: Main dining 60 chỗ với ceiling moulding tinh xảo, Private dining 12 chỗ với tường kính rượu vang temperature-controlled, và Bar lounge với cocktail counter marble Nero Marquina. Âm thanh cách ly hoàn toàn giữa các khu.','Ánh sáng warm 2700K tạo cảm giác ấm cúng lãng mạn. Tranh sơn mài Việt Nam trên tường panel gỗ sẫm. Chi phí 1.2 tỷ đồng, hoàn thành 75 ngày. Michelin Guide recommend 2025.']},
  {t:'Boutique Hotel Coco Đà Nẵng 450m²',c:'Nhà hàng & Khách sạn',s:'Coastal Modern',a:'450m²',l:'Đà Nẵng',y:2025,f:false,d:'Boutique hotel 15 phòng concept Coastal Serenity.',ps:['Hotel Coco là boutique hotel 15 phòng tại Mỹ Khê, Đà Nẵng. Concept Coastal Serenity — mỗi phòng là trải nghiệm biển khác nhau nhưng đồng nhất trong sự thanh bình. Palette xanh dương, trắng, cát xuyên suốt với vật liệu tự nhiên.','Lobby mở với quầy check-in từ gỗ lũa biển. Rooftop bar nhìn ra biển Mỹ Khê. Spa 3 phòng treatment sử dụng sản phẩm organic từ nghệ sĩ thủ công địa phương. Bể bơi tràn viền tầng 5 với sunset view.','Mỗi phòng có artwork riêng từ nghệ sĩ Đà Nẵng, gỗ driftwood, vải linen, đá cuội trang trí. Chi phí nội thất 2.1 tỷ đồng. TripAdvisor rating 4.8/5 sau 6 tháng vận hành.']},
  {t:'Căn Hộ Masteri Thảo Điền 70m²',c:'Căn hộ',s:'Japanese Minimalist',a:'70m²',l:'Quận 2, HCM',y:2025,f:false,d:'2PN tối ưu diện tích với Japanese Minimalist.',ps:['Căn hộ 70m² Masteri chứng minh không gian nhỏ không cần hy sinh phong cách. Japanese Minimalist giúp mỗi mét vuông đều có ý nghĩa và chức năng rõ ràng. Nội thất đa năng: giường có ngăn kéo, bàn ăn gấp gắn tường, sofa giường cho khách.','Tông trung tính: trắng, beige, gỗ nhạt tạo cảm giác rộng rãi thoáng mát. Tủ âm tường chiếm toàn bộ một mặt hành lang tối ưu lưu trữ. Phòng tắm kiểu Nhật với bồn ngâm ofuro nhỏ gọn, gạch terrazzo và indirect lighting.','Bếp chữ I tối ưu động line nấu nướng cho 2 người cùng lúc. Chi phí 280 triệu đồng — phù hợp ngân sách cặp vợ chồng trẻ. Hoàn thành chỉ 30 ngày làm việc.']},
  {t:'Biệt Thự Thảo Điền Compound 420m²',c:'Biệt thự',s:'Modern Classic',a:'420m²',l:'Quận 2, HCM',y:2024,f:true,d:'Biệt thự Modern Classic cho gia đình 3 thế hệ.',ps:['Biệt thự Thảo Điền Compound là công trình quy mô lớn nhất VietNet 2024 — 420m² cho gia đình 3 thế hệ. Modern Classic kết hợp trang nhã cổ điển với tiện nghi đương đại. Cầu thang xoắn marble Carrara là trung tâm ngôi nhà.','Phòng khách double-height với đèn chùm 2m và kệ sách cao đến trần. Hồ bơi vô cực trong vườn nhiệt đới 80m². Mỗi thế hệ có không gian riêng: ông bà tầng 1, bố mẹ tầng 2, con cái tầng 3 với study room. Thang máy gia đình kết nối 3 tầng.','Đá marble Ý, gỗ óc chó Mỹ, đồng thau cho hardware cao cấp. Chi phí 4.5 tỷ đồng — dự án giá trị cao nhất năm 2024 của VietNet Interior.']},
  {t:'Showroom VietNet Interior 300m²',c:'Văn phòng',s:'Gallery Concept',a:'300m²',l:'Quận 3, HCM',y:2025,f:true,d:'Showroom nội thất concept gallery nghệ thuật sống.',ps:['Showroom VietNet tại Quận 3 không chỉ trưng bày sản phẩm — đó là trải nghiệm nghệ thuật sống. Concept Gallery biến mỗi góc thành không gian sống hoàn chỉnh để khách hàng cảm nhận trực tiếp chất lượng thiết kế.','6 phòng themed: Scandinavian Living, Indochine Elegance, Tropical Retreat, Modern Luxury, Japanese Zen, Industrial Loft. Mỗi phòng có ánh sáng, mùi hương và âm nhạc riêng. Tầng lửng là Design Studio có VR 360° và material library 500+ mẫu.','Chi phí fit-out 1.6 tỷ đồng. Lượng khách 300 người/tháng, tỷ lệ chuyển đổi 18% — cao gấp 3 trung bình ngành nội thất.']},
  {t:'Căn Hộ The Marq Quận 1 120m²',c:'Căn hộ',s:'Art Deco',a:'120m²',l:'Quận 1, HCM',y:2025,f:false,d:'Art Deco lấy cảm hứng thập niên 1920s.',ps:['The Marq là dự án hạng A+ tiêu chuẩn quốc tế. VietNet thiết kế Art Deco — cảm hứng 1920s diễn giải đương đại. Đường cong hình học, metallic accent vàng đồng, gương bevel-cut và velvet emerald green tạo nên sự sang trọng cổ điển.','Sàn herringbone walnut, tường wallpaper geometric. Phòng khách-bếp 50m² với bar counter bọc da. Master bedroom vanity area Hollywood-style. 2 phòng tắm đá marble đen vân trắng Nero Marquina.','Chi phí 680 triệu cho 120m² phân khúc luxury. Hoàn thành 50 ngày. Được feature trên tạp chí Kiến Trúc & Đời Sống.']},
  {t:'Nhà Phố Thủ Đức 4 Tầng 180m²',c:'Biệt thự',s:'Modern Minimalist',a:'180m²',l:'TP. Thủ Đức',y:2025,f:false,d:'Nhà phố 4 tầng tối giản, thiết kế đẹp giá hợp lý.',ps:['Nhà phố 4 tầng là dự án mid-range tiêu biểu — chứng minh thiết kế đẹp không nhất thiết đắt đỏ. Modern Minimalist phù hợp gia đình trẻ 4 người. Tầng 1: garage, khách, bếp-ăn mở. Tầng 2: master và phòng con trai. Tầng 3: phòng con gái và thư viện.','Gam trắng-xám-gỗ xuyên suốt. Cầu thang thép thanh mảnh chiếm ít diện tích. Bếp acrylic trắng bóng dễ vệ sinh. Track lighting thay trần thạch cao, vừa đẹp vừa tiết kiệm chi phí đáng kể.','Chi phí 380 triệu cho 180m² — budget-friendly cho gia đình trung lưu. Hoàn thành 40 ngày. Gia chủ giới thiệu thêm 3 khách hàng mới cho VietNet.']},
  {t:'Spa & Wellness Center 250m²',c:'Nhà hàng & Khách sạn',s:'Zen Japanese',a:'250m²',l:'Quận 2, HCM',y:2025,f:false,d:'Spa Zen Japanese với 5 phòng treatment ngũ hành.',ps:['Spa & Wellness tại Thảo Điền mang phong cách Zen Japanese — nơi tìm lại cân bằng giữa nhịp sống hối hả. 5 phòng treatment theo ngũ hành: Mộc (gỗ), Hỏa (nến), Thổ (đá), Kim (metallic), Thủy (nước). Reception bonsai garden và hồ cá Koi.','Gỗ hinoki Nhật, đá basalt, sỏi trắng, tre tự nhiên. Ánh sáng gián tiếp 2400K. Hệ thống Bose nature sounds. Mùi hinoki tự nhiên lan tỏa nhẹ nhàng qua hệ thống khuếch tán tinh dầu.','Chi phí 1.1 tỷ đồng. Doanh thu tháng đầu vượt 40% dự kiến nhờ trải nghiệm không gian xuất sắc — khách hàng quay lại 78%.']},
  {t:'Văn Phòng Luật Baker McKenzie 400m²',c:'Văn phòng',s:'Corporate Elegant',a:'400m²',l:'Quận 1, HCM',y:2024,f:false,d:'Văn phòng luật quốc tế tiêu chuẩn Fortune 500.',ps:['Baker McKenzie — hãng luật top 10 thế giới. Văn phòng Sài Gòn thể hiện chuyên nghiệp, uy tín nhưng ấm áp. Corporate Elegant: gỗ óc chó panel tường và bàn họp, marble sảnh reception, thảm len New Zealand.','Reception grand 60m² logo backlit ấn tượng. 4 phòng họp 8-20 người với AV Crestron. 15 văn phòng partner/associate. Library room kệ sách pháp luật floor-to-ceiling. Navy, cream và brass tạo cảm giác tin cậy.','Chi phí 2.2 tỷ đồng. Global Management Team đánh giá "best office in Southeast Asia region" — tiêu chuẩn benchmark cho các văn phòng Baker McKenzie khác.']},
  {t:'Duplex Feliz En Vista 150m²',c:'Căn hộ',s:'Wabi-Sabi',a:'150m²',l:'Quận 2, HCM',y:2025,f:false,d:'Wabi-Sabi — vẻ đẹp của sự không hoàn hảo.',ps:['Duplex Feliz En Vista phong cách Wabi-Sabi — tôn vinh vẻ đẹp không hoàn hảo và sự trôi qua của thời gian. Bê tông trần không sơn, gỗ có vân nứt tự nhiên, gốm handmade glaze không đều, linen nhăn tự nhiên.','Tầng dưới: living-dining mở với cầu thang gỗ lũa organic. Tầng trên: 2 phòng ngủ và studio vẽ tranh cho chủ nhà họa sĩ. Ban công 15m² vườn xương rồng và bonsai. Không có đường thẳng hoàn hảo — mọi thứ asymmetric.','Chi phí 520 triệu — Wabi-Sabi tưởng đơn giản nhưng đòi hỏi craftmanship cao. 45 ngày hoàn thành. Dự án được trưng bày tại triển lãm Design Week Saigon.']},
  {t:'Rooftop Bar Cloud Nine 200m²',c:'Nhà hàng & Khách sạn',s:'Neo-Tropical',a:'200m²',l:'Quận 1, HCM',y:2025,f:true,d:'Rooftop bar tầng 30 với view 360° Sài Gòn.',ps:['Cloud Nine là rooftop bar tầng 30 cung cấp view 360° thành phố về đêm. Neo-Tropical — nhiệt đới nhưng tinh tế hiện đại. Chuối cảnh, monstera trong chậu concrete. Rattan kết hợp đồng thau. Fairy lights và neon custom.','Bar counter 8m terrazzo xanh ngọc. DJ booth chuyên nghiệp. 3 khu: Lounge sofa ấm cúng, High table standing cho networking, VIP cabana riêng tư. Sức chứa 120 khách. Hệ thống JBL Professional.','Chi phí 1.4 tỷ đồng. Saigon Nightlife Award bình chọn Best New Bar 2025. Revenue tháng đầu đạt 1.2 tỷ — ROI 10 tháng.']},
  {t:'Căn Hộ Estella Heights 95m²',c:'Căn hộ',s:'Mid-Century Modern',a:'95m²',l:'Quận 2, HCM',y:2024,f:false,d:'Mid-Century Modern hoài cổ thập niên 60s.',ps:['Estella Heights lấy cảm hứng 1960s — thời kỳ vàng Mid-Century Modern. Chủ nhà collector đồ vintage yêu cầu thiết kế authentic nhưng liveable. Ghế Eames Lounge replica, bàn Noguchi, đèn Arco. Mustard yellow và teal.','Sàn herringbone walnut. Kệ vinyl records và turntable. Bếp retro laminate pastel và countertop formica. Master bedroom blush pink với vanity Hollywood-style. 2 phòng tắm retro subway tiles.','Chi phí 420 triệu bao gồm sourcing vintage. Feature trên tạp chí Kiến Trúc & Đời Sống số tháng 3/2025.']},
  {t:'Biệt Thự Ecopark Grand 500m²',c:'Biệt thự',s:'Contemporary Zen',a:'500m²',l:'Hưng Yên',y:2025,f:true,d:'Biệt thự vườn Contemporary Zen giữa thiên nhiên.',ps:['Ecopark Grand — 500m² gồm nhà chính, nhà kho vườn, bể bơi và sân vườn Zen. Triết lý Living with Nature. Không gian mở hòa vào cảnh quan qua tường kính xóa ranh giới trong-ngoài.','Vườn Zen Nhật: đá, sỏi, rêu và maple Nhật. Ao cá Koi 15m² tại sảnh chính. Bê tông trần, gỗ ash, đá bazan đen, kính low-iron. Nội thất tối giản — mỗi phòng chỉ đồ cần thiết. Giếng trời và clerestory windows.','Chi phí 3.8 tỷ đồng. 5 tháng thi công do phức tạp landscaping và cây cảnh Nhật nhập khẩu. Dự án đoạt giải Green Building Award 2025.']},
  {t:'Food Court AEON Mall 600m²',c:'Nhà hàng & Khách sạn',s:'Modern Asian',a:'600m²',l:'Bình Tân, HCM',y:2025,f:false,d:'Food court 300 chỗ phong cách ẩm thực đường phố châu Á.',ps:['Food court AEON Bình Tân — 600m², 300 chỗ, 2000+ lượt khách/ngày. Modern Asian pha trộn ẩm thực đường phố châu Á. 12 quầy themed: Phở Việt, Sushi Bar, Korean BBQ, Thai Street, Chinese Wok và nhiều hơn.','Seating đa dạng: bar stool, booth gia đình, communal table 16 người, khu ngoài trời giả với cây xanh. Trần trang trí đèn lồng và cây treo tạo cảm giác phố ẩm thực ngoài trời sống động.','Chi phí 2.5 tỷ cho 600m². 90 ngày kịp khai trương AEON Mall. Doanh thu F&B tăng 35% so với food court thiết kế cũ — chứng minh ROI của thiết kế chất lượng.']},
];

const ARTICLES = [
  {t:'5 Xu Hướng Thiết Kế Nội Thất 2025 Không Thể Bỏ Qua',c:'Xu hướng thiết kế',f:true,d:'Japandi, Quiet Luxury, vật liệu tái chế — xu hướng nội thất 2025.',ps:['Năm 2025 đánh dấu sự chuyển mình mạnh mẽ trong ngành thiết kế nội thất Việt Nam. Từ phong cách Japandi đến Quiet Luxury, các xu hướng mới không chỉ theo đuổi vẻ đẹp mà còn đề cao tính bền vững và sức khỏe tinh thần.','Japandi tiếp tục thống trị — kết hợp tối giản Nhật Bản với ấm áp Bắc Âu. Quiet Luxury thay thế sự phô trương bằng chất lượng vật liệu và craftsmanship. Biophilic Design đưa thiên nhiên vào nhà qua cây xanh, ánh sáng tự nhiên và vật liệu hữu cơ.','Curved Furniture với đường cong mềm mại thay thế góc cạnh sắc nhọn. Vật liệu tái chế và bền vững trở thành tiêu chuẩn — từ gỗ reclaimed đến vải organic. VietNet Interior dẫn đầu áp dụng 5 xu hướng này trong mọi dự án.']},
  {t:'Hướng Dẫn Chọn Màu Sơn Phòng Khách Theo Phong Thủy',c:'Kiến thức nội thất',f:false,d:'Chọn màu sơn phòng khách phù hợp mệnh và hướng nhà.',ps:['Màu sắc phòng khách không chỉ ảnh hưởng thẩm mỹ mà còn tác động vận khí gia đình theo phong thủy. Mệnh Kim nên chọn trắng, xám, bạc. Mệnh Mộc phù hợp xanh lá, nâu gỗ. Mệnh Thủy chọn xanh dương, đen. Mệnh Hỏa dùng đỏ, cam, tím. Mệnh Thổ chọn vàng, nâu đất.','Ngoài mệnh bản thân, cần xét hướng nhà. Phòng khách hướng Bắc (Thủy) nên dùng màu trắng Kim sinh Thủy. Hướng Nam (Hỏa) dùng xanh lá Mộc sinh Hỏa. Tránh dùng màu khắc: phòng hướng Đông Bắc (Thổ) không nên sơn xanh lá (Mộc khắc Thổ).','Thực tế, VietNet Interior khuyên kết hợp phong thủy với thẩm mỹ hiện đại. Dùng tone chính theo phong thủy, kết hợp accent colors theo sở thích cá nhân. Tránh sơn toàn bộ phòng một màu — phối 2-3 tone trong cùng họ màu để tạo chiều sâu.']},
  {t:'So Sánh Gỗ Óc Chó vs Gỗ Sồi: Nên Chọn Loại Nào?',c:'Kiến thức nội thất',f:true,d:'Phân tích ưu nhược điểm 2 loại gỗ cao cấp phổ biến nhất.',ps:['Gỗ óc chó (walnut) và gỗ sồi (oak) là hai loại gỗ phổ biến nhất trong nội thất cao cấp Việt Nam. Gỗ óc chó có màu nâu sô-cô-la đặc trưng, vân gỗ mềm mại, giá 15-25 triệu/m³. Gỗ sồi có màu sáng hơn, vân thẳng rõ nét, giá 8-15 triệu/m³.','Về độ cứng, gỗ sồi cứng hơn (Janka 1360 vs 1010) — phù hợp sàn nhà, cầu thang. Gỗ óc chó mềm hơn nhưng dễ gia công, phù hợp nội thất cong và chi tiết tinh xảo. Cả hai đều bền 50+ năm nếu bảo quản đúng cách.','VietNet Interior khuyên: gỗ sồi cho phong cách Scandinavian, Modern Minimalist. Gỗ óc chó cho Indochine, Mid-Century Modern, Luxury. Có thể kết hợp cả hai — sàn sồi + nội thất óc chó tạo contrast đẹp mắt.']},
  {t:'Thiết Kế Phòng Ngủ Nhỏ 10m² Vẫn Đẹp Và Tiện Nghi',c:'Chia sẻ kinh nghiệm',f:false,d:'8 mẹo thiết kế thông minh cho phòng ngủ nhỏ.',ps:['Không gian nhỏ không có nghĩa phải hy sinh phong cách. 8 mẹo từ VietNet Interior: (1) Giường có ngăn kéo hoặc giường tầng đa năng. (2) Tủ âm tường tận dụng chiều cao trần. (3) Gương lớn tạo ảo giác không gian gấp đôi.','(4) Tông màu sáng cho tường và trần — trắng, kem, pastel. (5) Đèn indirect lighting thay đèn trần cồng kềnh. (6) Bàn gấp gắn tường kiêm bàn làm việc. (7) Rèm sát trần tạo chiều cao thị giác. (8) Kệ nổi thay tủ đầu giường.','Case study thực tế: phòng ngủ 9.5m² tại căn hộ Masteri Thảo Điền — sau khi áp dụng 8 mẹo trên, gia chủ ngỡ ngàng vì phòng trông rộng gần gấp đôi. Chi phí chỉ thêm 15 triệu cho nội thất đa năng.']},
  {t:'VietNet Interior Hoàn Thành Dự Án Biệt Thự Lucasta',c:'Tin tức VietNet',f:true,d:'Khánh thành dự án Indochine 350m² sau 4 tháng thi công.',ps:['VietNet Interior tự hào giới thiệu dự án biệt thự Lucasta Khang Điền — công trình phong cách Indochine đương đại 350m², sử dụng hoàn toàn gỗ óc chó Mỹ nhập khẩu. Đây là dự án phức tạp nhất năm 2024.','4 tháng thi công với đội ngũ 25 thợ lành nghề. Thách thức lớn nhất là cầu thang xoắn ốc gỗ óc chó — 36 bậc uốn cong hoàn hảo, mỗi bậc là một tác phẩm thủ công riêng. Gạch bông handmade đặt riêng từ làng nghề Bình Dương.','Gia chủ — anh Minh Hoàng, doanh nhân ngành F&B — chia sẻ: "VietNet biến ước mơ về ngôi nhà Đông Dương thành hiện thực. Mỗi góc nhà đều kể một câu chuyện." Dự án đánh dấu bước tiến quan trọng trong phân khúc biệt thự cao cấp.']},
  {t:'Bí Quyết Bảo Quản Nội Thất Gỗ Trong Mùa Mưa',c:'Chia sẻ kinh nghiệm',f:false,d:'Hướng dẫn chống ẩm, chống mốc cho đồ gỗ mùa mưa.',ps:['Thời tiết ẩm ướt miền Nam Việt Nam là kẻ thù số 1 của nội thất gỗ. VietNet Interior chia sẻ kinh nghiệm 10 năm bảo quản: Độ ẩm lý tưởng 45-65%, dùng máy hút ẩm khi >70%. Lau gỗ bằng khăn khô mềm, tránh nước đọng.','Wax bảo dưỡng 3 tháng/lần cho gỗ tự nhiên. Tránh kê sát tường — cách ít nhất 5cm cho không khí lưu thông. Sàn gỗ dùng giẻ lau hơi ẩm, KHÔNG dùng nước nhiều. Kiểm tra chân bàn ghế thường xuyên — mối mọt thường tấn công từ dưới lên.','Nếu phát hiện mốc sớm: dùng giấm trắng + nước ấm (1:1) lau sạch, phơi nắng nhẹ. Mốc nặng cần thợ chuyên nghiệp xử lý. VietNet cung cấp dịch vụ bảo trì nội thất định kỳ với chi phí từ 2 triệu/lần.']},
  {t:'Phong Cách Japandi: Sự Kết Hợp Hoàn Hảo Nhật - Bắc Âu',c:'Xu hướng thiết kế',f:true,d:'Nguyên tắc, bảng màu và cách áp dụng Japandi cho nhà Việt.',ps:['Japandi = Japanese + Scandinavian — xu hướng kết hợp wabi-sabi Nhật Bản với hygge Bắc Âu. Tối giản nhưng ấm áp, chức năng nhưng có hồn. Bảng màu: trắng ngà, beige, xám ấm, nâu gỗ nhạt, xanh rêu nhẹ.','3 nguyên tắc cốt lõi: (1) Form follows function — mỗi đồ vật phải có mục đích sử dụng. (2) Natural materials — gỗ, linen, ceramic, giấy washi. (3) Craftsmanship — ưu tiên handmade, imperfect beauty. Tránh: nhựa, metallic bóng, hoa văn phức tạp.','Áp dụng cho căn hộ Việt Nam: phòng khách dùng sofa vải linen tông kem, bàn gỗ ash, thảm jute. Phòng ngủ futon hoặc giường thấp platform, ga trải linen, đèn Akari giấy. VietNet đã hoàn thành 15 dự án Japandi trong năm 2024-2025.']},
  {t:'Chi Phí Thiết Kế Nội Thất Căn Hộ 2025: Bảng Giá Chi Tiết',c:'Kiến thức nội thất',f:false,d:'Tổng hợp chi phí thiết kế thi công nội thất các phân khúc.',ps:['Chi phí nội thất căn hộ 2025 chia 3 phân khúc: Bình dân 3-5 triệu/m² (vật liệu công nghiệp, MDF, laminate). Trung cấp 5-10 triệu/m² (gỗ công nghiệp cao cấp An Cường, đá nhân tạo, thiết bị Hafele). Cao cấp 10-25 triệu/m² (gỗ tự nhiên, đá marble, thiết bị châu Âu).','Ví dụ căn hộ 70m²: Bình dân 210-350 triệu. Trung cấp 350-700 triệu. Cao cấp 700-1.75 tỷ. Chi phí thiết kế riêng: 100-300K/m² tùy hãng. VietNet Interior miễn phí thiết kế khi thi công trọn gói.','Tips tiết kiệm từ VietNet: (1) Ưu tiên vật liệu tốt cho bếp và phòng tắm — nơi dùng nhiều nhất. (2) Phòng ngủ có thể dùng MDF chống ẩm thay gỗ tự nhiên. (3) Đèn LED âm trần rẻ hơn và đẹp hơn trần thạch cao trang trí.']},
  {t:'Smart Home: Tích Hợp Công Nghệ Vào Nội Thất Hiện Đại',c:'Xu hướng thiết kế',f:false,d:'Cách VietNet tích hợp smart home mà giữ thẩm mỹ.',ps:['Smart home không phải xa xỉ — từ 30 triệu đồng có thể biến căn hộ thành nhà thông minh. VietNet Interior tích hợp: đèn Philips Hue điều khiển bằng giọng nói, rèm tự động Somfy, khóa vân tay Samsung, camera IP Ezviz.','Thách thức lớn nhất: ẩn dây điện và thiết bị. VietNet giải quyết bằng hệ thống ống luồn dây trong tường, công tắc âm tường Xiaomi Aqara, và speaker loa Sonos gắn trần không lộ dây. Switch panel custom khớp với tường.','Hệ sinh thái VietNet Smart Home: Google Home / Apple HomeKit tùy chọn. Kịch bản "Good Morning" tự động mở rèm, bật đèn warm, pha cà phê. "Movie Night" tắt đèn, hạ rèm, bật projector. Tiết kiệm 30% điện năng qua automation.']},
  {t:'VietNet Interior Nhận Giải "Best Interior Design 2025"',c:'Tin tức VietNet',f:true,d:'Đạt giải thưởng uy tín Vietnam Property Awards 2025.',ps:['VietNet Interior vinh dự nhận giải "Best Interior Design" tại Vietnam Property Awards 2025 với dự án Penthouse Midtown Phú Mỹ Hưng 200m². Ban giám khảo quốc tế đánh giá cao sự sáng tạo, chất lượng vật liệu và attention to detail.','Đây là lần thứ hai VietNet nhận giải thưởng quốc tế — sau giải "Rising Star" năm 2023. CEO Quân Bùi chia sẻ: "Giải thưởng này thuộc về cả đội ngũ 35 kiến trúc sư và thợ lành nghề. Chúng tôi cam kết tiếp tục nâng cao chất lượng thiết kế Việt Nam lên tầm quốc tế."','VietNet Interior hiện phục vụ hơn 200 khách hàng/năm tại TP.HCM, Đà Nẵng và Hà Nội. Năm 2026, công ty dự kiến mở showroom tại Đà Nẵng và ra mắt dịch vụ thiết kế online cho khách hàng toàn quốc.']},
  {t:'Cách Chọn Sofa Phù Hợp Cho Phòng Khách Nhỏ',c:'Chia sẻ kinh nghiệm',f:false,d:'Hướng dẫn chọn size, kiểu dáng và chất liệu sofa cho phòng nhỏ.',ps:['Sofa chiếm 30-40% diện tích phòng khách — chọn sai size sẽ khiến phòng chật chội. Quy tắc vàng: sofa chiều dài không quá 2/3 bề ngang phòng. Phòng khách 12m² chọn sofa 2 chỗ 1.5-1.8m. Phòng 20m² dùng sofa góc L.','Kiểu dáng: sofa chân cao tạo cảm giác thoáng (nhìn thấy sàn dưới sofa). Tay vịn mỏng tiết kiệm 10-15cm chiều rộng. Sofa modular có thể tách ghép linh hoạt theo nhu cầu. Tránh sofa quá sâu (>90cm) trong phòng nhỏ.','Chất liệu: vải microfiber dễ vệ sinh, phù hợp gia đình có trẻ nhỏ. Da thật sang trọng nhưng cần bảo dưỡng. Vải linen tự nhiên cho phong cách Japandi. VietNet cung cấp dịch vụ tư vấn miễn phí và mang mẫu vải đến nhà.']},
  {t:'Xu Hướng Bếp Mở 2025: Ưu Nhược Điểm Và Cách Thiết Kế',c:'Xu hướng thiết kế',f:false,d:'Phân tích xu hướng bếp mở và giải pháp cho gia đình Việt.',ps:['Bếp mở (open kitchen) đang trở thành tiêu chuẩn tại căn hộ hiện đại. Ưu điểm: tạo không gian rộng rãi, kết nối gia đình khi nấu nướng, ánh sáng tự nhiên tốt hơn. Nhược điểm: mùi thức ăn lan ra phòng khách, tiếng ồn, cần gọn gàng liên tục.','Giải pháp VietNet cho gia đình Việt thích nấu: (1) Hút mùi công suất lớn 900-1200 m³/h đặt âm trần. (2) Bếp từ thay bếp gas giảm 70% khói. (3) Vách kính trượt mở-đóng linh hoạt — mở khi tiếp khách, đóng khi nấu. (4) Đảo bếp làm ranh giới thị giác.','Chi phí upgrade bếp truyền thống sang bếp mở: 80-150 triệu tùy quy mô. Thời gian 15-20 ngày. VietNet đảm bảo không ảnh hưởng kết cấu tòa nhà — tất cả phá tường đều được kỹ sư kết cấu kiểm tra trước.']},
  {t:'Review Vật Liệu Đá Thạch Anh Nhân Tạo Cho Bếp',c:'Kiến thức nội thất',f:false,d:'So sánh các thương hiệu đá thạch anh phổ biến tại Việt Nam.',ps:['Đá thạch anh nhân tạo (quartz) đang thay thế đá granite tự nhiên cho mặt bếp nhờ ưu điểm: không thấm nước, không cần seal, chống khuẩn, đa dạng màu sắc. Top 5 thương hiệu tại VN: Caesarstone (Israel), Silestone (Tây Ban Nha), Vicostone (Việt Nam), Samsung Radianz, Cambria.','Giá: Vicostone 3-5 triệu/m² (made in Vietnam, chất lượng quốc tế). Caesarstone 6-12 triệu/m². Silestone 8-15 triệu/m². Thickness phổ biến: 20mm cho bếp, 30mm cho đảo bếp. VietNet khuyên Vicostone cho ngân sách tối ưu — chất lượng tương đương 80% hàng nhập.','Lưu ý: đá thạch anh chịu nhiệt đến 150°C — KHÔNG đặt nồi nóng trực tiếp. Tránh dùng dao cắt trực tiếp trên mặt đá. Vệ sinh bằng nước ấm + xà phòng nhẹ. Bảo hành 10-15 năm tùy hãng.']},
  {t:'Trang Trí Nhà Đón Tết 2026: Ý Tưởng Hiện Đại',c:'Chia sẻ kinh nghiệm',f:true,d:'20 ý tưởng trang trí Tết vừa truyền thống vừa hiện đại.',ps:['Tết 2026 không cần phải chọn giữa truyền thống và hiện đại — VietNet Interior chia sẻ cách kết hợp cả hai. Hoa mai vàng trong bình ceramic minimalist. Câu đối đỏ viết bằng font calligraphy hiện đại trên giấy kraft. Mâm ngũ quả trên khay gỗ tối giản.','Đèn trang trí: thay đèn lồng đỏ truyền thống bằng đèn paper lantern tông warm white. Cành đào trong lọ thủy tinh cao. Rèm cửa thay mới tông đỏ đô hoặc vàng đồng — sang trọng mà không lòe loẹt. Thảm trải sàn đỏ accent cho phòng khách.','Budget-friendly: 5-10 triệu đồng cho toàn bộ trang trí Tết. Mua hoa và cành tại chợ hoa Tết (rẻ hơn shop 50%). DIY thiệp và câu đối. VietNet cung cấp gói trang trí Tết trọn gói từ 3 triệu đồng cho căn hộ.']},
  {t:'Lỗi Thiết Kế Nội Thất Phổ Biến Và Cách Khắc Phục',c:'Kiến thức nội thất',f:false,d:'10 lỗi thường gặp khi tự thiết kế nội thất.',ps:['10 lỗi phổ biến VietNet Interior thường gặp khi khách hàng tự thiết kế: (1) Nội thất quá lớn so với phòng. (2) Thiếu ánh sáng tầng — chỉ có đèn trần, không có đèn bàn/đèn sàn. (3) Treo tranh quá cao — tâm tranh nên ngang tầm mắt 150cm.','(4) Thảm quá nhỏ — thảm phòng khách phải đủ lớn để chân trước sofa đặt trên thảm. (5) Quá nhiều màu — tối đa 3 màu chủ đạo. (6) Bỏ qua storage — thiếu tủ lưu trữ khiến nhà bừa bộn. (7) Rèm quá ngắn — rèm phải chạm sàn hoặc cách sàn 1cm.','(8) Đèn sai nhiệt độ màu — phòng ngủ dùng warm 2700K, không dùng cool 6500K. (9) Bố trí nội thất ép sát tường — nên kéo sofa cách tường 15-30cm. (10) Quên lối đi — giữ tối thiểu 90cm cho lối đi chính.']},
  {t:'VietNet Interior Mở Rộng Dịch Vụ Tại Đà Nẵng',c:'Tin tức VietNet',f:false,d:'Khai trương showroom và đội ngũ thiết kế tại Đà Nẵng.',ps:['VietNet Interior chính thức mở rộng hoạt động tại Đà Nẵng từ tháng 4/2026 với showroom 200m² tại đường Nguyễn Văn Linh và đội ngũ 8 kiến trúc sư. Đây là bước tiến quan trọng trong chiến lược phủ sóng toàn quốc.','Đà Nẵng được chọn vì thị trường nội thất đang bùng nổ — bất động sản nghỉ dưỡng tăng 40% năm qua. VietNet đã hoàn thành 5 dự án tại Đà Nẵng: Hotel Coco, 2 villa biển và 2 căn hộ cao cấp. Khách hàng Đà Nẵng yêu cầu phong cách Coastal Modern và Tropical chiếm 70%.','Ưu đãi khai trương: giảm 15% phí thiết kế cho 20 khách hàng đầu tiên. Tư vấn miễn phí tại nhà trong nội thành Đà Nẵng. Liên hệ hotline 0901 234 567 hoặc email danang@vietnetinterior.vn.']},
  {t:'Đánh Giá Top 5 Hãng Sơn Nội Thất Tốt Nhất 2025',c:'Kiến thức nội thất',f:false,d:'So sánh Dulux, Jotun, Nippon, TOA, Kansai cho nội thất.',ps:['Sơn chiếm 5-10% chi phí nội thất nhưng ảnh hưởng 80% thẩm mỹ tổng thể. Top 5 hãng sơn VietNet khuyên dùng: (1) Dulux Weathershield — sơn ngoại thất số 1, bền màu 7 năm. (2) Jotun Majestic — sơn nội thất premium, lau chùi dễ dàng, ít VOC.','(3) Nippon Matex — giá tốt nhất phân khúc trung cấp, che phủ tốt, nhanh khô. (4) TOA NanoShield — công nghệ nano tự làm sạch, phù hợp nhà có trẻ nhỏ. (5) Kansai Alesco — sơn Nhật cao cấp, độ bám dính xuất sắc, bảng màu tinh tế.','Giá trung bình: 180-350K/lít cho loại 5 trong 1. Chi phí sơn căn hộ 70m² (2 lớp lót + 2 lớp phủ): 8-15 triệu đồng bao gồm nhân công. VietNet Interior hợp tác chính hãng Jotun và Dulux — đảm bảo sơn chính hãng, pha màu chuẩn.']},
  {t:'Thiết Kế Phòng Tắm Hiện Đại: Từ Bình Dân Đến Cao Cấp',c:'Chia sẻ kinh nghiệm',f:false,d:'Hướng dẫn thiết kế phòng tắm 3 phân khúc giá.',ps:['Phòng tắm là nơi bắt đầu và kết thúc mỗi ngày — đầu tư đúng mang lại hạnh phúc lâu dài. Bình dân (15-30 triệu): gạch 30x60 đơn sắc, thiết bị Viglacera/Inax, tủ lavabo MDF chống ẩm, vòi sen tay cầm TOTO cơ bản.','Trung cấp (30-60 triệu): gạch 60x120 vân đá, thiết bị Kohler/American Standard, tủ lavabo gỗ công nghiệp, rain shower, gương đèn LED, kính cường lực vách tắm. Cao cấp (60-150 triệu): đá marble thật, thiết bị Grohe/Hansgrohe/Villeroy & Boch, bồn tắm freestanding, heated floor, smart toilet.','Tips từ VietNet: (1) Chống thấm LUÔN ưu tiên — tiết kiệm ở đây sẽ trả giá đắt. (2) Ốp gạch 60x120 ít ron hơn 30x30, dễ lau chùi, sang hơn. (3) Hố ga đặt đúng vị trí — nước phải chảy về hố ga tự nhiên, không đọng.']},
  {t:'Hướng Dẫn Đo Đạc Căn Hộ Trước Khi Thiết Kế',c:'Kiến thức nội thất',f:false,d:'Cách tự đo căn hộ chính xác để tối ưu thiết kế nội thất.',ps:['Đo đạc chính xác là bước đầu tiên quan trọng nhất — sai 5cm có thể khiến tủ không vừa hoặc cửa không mở được. Dụng cụ cần: thước laser (Bosch GLM 30 từ 800K), thước cuộn 5m, giấy bút ghi chép.','Quy trình đo VietNet: (1) Đo tổng diện tích từng phòng — dài x rộng. (2) Đo vị trí cửa ra vào, cửa sổ, ban công — khoảng cách từ tường đến cạnh cửa. (3) Đo chiều cao trần (thường 2.7-3.2m). (4) Đánh dấu vị trí ổ điện, switch, ống nước. (5) Chụp ảnh toàn bộ mỗi góc phòng.','Gửi bản đo cho VietNet Interior — chúng tôi sẽ tư vấn layout miễn phí trong 24h. Email: measure@vietnetinterior.vn. Hoặc đặt lịch đo miễn phí tại nhà — kiến trúc sư đến đo laser 3D chính xác đến 1mm.']},
];

const PRODUCTS = [
  {t:'Sofa Góc L Scandinavian',c:'Sofa & Ghế',p:28500000,d:'Sofa góc L vải linen tự nhiên phong cách Bắc Âu, khung gỗ sồi.',ps:['Sofa góc L Scandinavian là sản phẩm bán chạy nhất của VietNet Interior năm 2025. Khung gỗ sồi tự nhiên chắc chắn, đệm foam HR cao cấp bọc vải linen Bỉ thoáng mát. Kích thước 2.8m x 1.7m phù hợp phòng khách từ 15m².','Thiết kế tay vịn mỏng tiết kiệm diện tích. Chân gỗ cao 15cm dễ vệ sinh dưới sofa. Đệm có khóa kéo tháo giặt. Màu sắc: Oat Cream, Sage Green, Warm Grey. Bảo hành khung 5 năm, đệm 2 năm.']},
  {t:'Ghế Ăn Eames Replica',c:'Sofa & Ghế',p:2800000,d:'Ghế ăn nhựa PP phong cách Mid-Century, chân gỗ sồi.',ps:['Ghế Eames DSW replica chất lượng cao — nhựa PP nguyên sinh chịu lực 120kg, chân gỗ sồi Châu Âu với thanh giằng thép chrome. Thiết kế ergonomic ôm lưng tự nhiên, ngồi thoải mái 2+ giờ liên tục.','12 màu sắc từ classic (trắng, đen, xám) đến trendy (mustard, teal, blush pink). Stackable tiết kiệm diện tích khi không sử dụng. Phù hợp bàn ăn, bàn làm việc, quán café. Mua combo 4 ghế giảm 10%.']},
  {t:'Bàn Ăn Gỗ Sồi 6 Chỗ',c:'Bàn & Kệ',p:15800000,d:'Bàn ăn gỗ sồi tự nhiên 160x80cm, thiết kế tối giản.',ps:['Bàn ăn gỗ sồi FAS (First and Seconds) nhập khẩu Nga — hạng gỗ cao nhất, vân đẹp đồng đều. Kích thước 160x80x75cm cho 6 người thoải mái. Mặt bàn dày 30mm phủ dầu linseed tự nhiên, không sơn PU giữ vẻ đẹp thô mộc.','Chân bàn hình thang chữ A vững chắc, có miếng đệm chống xước sàn. Phong cách phù hợp: Scandinavian, Japandi, Modern Minimalist. Có thể kết hợp ghế Eames, ghế gỗ hoặc bench. Bảo hành 3 năm.']},
  {t:'Kệ Sách Tường Modular',c:'Bàn & Kệ',p:8500000,d:'Hệ kệ sách modular gắn tường, tùy chỉnh layout linh hoạt.',ps:['Kệ sách modular gồm 6 khối hộp kích thước khác nhau (30x30, 30x60, 60x30cm) gắn tường bằng rail nhôm. Chất liệu MDF chống ẩm phủ melamine vân gỗ sồi. Chịu tải 15kg/khối. Tổng chiều rộng 180cm, cao 120cm.','Tự do sắp xếp layout: đối xứng, lệch tầng, zigzag — thể hiện cá tính chủ nhà. Có thể mua thêm khối mở rộng. Đi kèm đèn LED strip gắn dưới mỗi khối. Lắp đặt tại nhà bởi đội ngũ VietNet trong 2 giờ.']},
  {t:'Tủ Quần Áo Âm Tường 2.4m',c:'Tủ & Lưu trữ',p:32000000,d:'Tủ âm tường cánh trượt gỗ công nghiệp cao cấp An Cường.',ps:['Tủ quần áo âm tường 2.4m rộng x 2.6m cao x 0.6m sâu — tận dụng tối đa chiều cao trần. Cánh trượt 3 cánh panel gỗ An Cường E1 (formaldehyde thấp, an toàn sức khỏe). Hệ thống ray trượt Blum Áo êm ái, chịu tải 80kg/cánh.','Nội thất bên trong tùy chỉnh: thanh treo đôi (áo ngắn), thanh treo đơn (áo dài), ngăn kéo, kệ giày, ngăn gấp. Phụ kiện Hafele: giá treo cravat, khay trang sức, đèn LED cảm ứng mở cửa tự sáng.']},
  {t:'Tủ Giày Thông Minh Xoay',c:'Tủ & Lưu trữ',p:12500000,d:'Tủ giày xoay 360° chứa 40 đôi trong không gian 0.6m².',ps:['Tủ giày xoay 360° là giải pháp lưu trữ thông minh cho căn hộ nhỏ. Chứa tối đa 40 đôi giày trong diện tích chỉ 60x60cm. Hệ trục xoay bearing thép chịu tải 80kg, xoay êm không tiếng ồn.','6 tầng kệ nghiêng 15° giữ giày không rơi. Vỏ ngoài MDF phủ acrylic trắng bóng hoặc vân gỗ. Có phiên bản có gương toàn thân mặt ngoài — 2 trong 1. Lắp đặt đơn giản, kèm hướng dẫn video.']},
  {t:'Đèn Thả Bàn Ăn Brass',c:'Đèn & Phụ kiện',p:4500000,d:'Đèn thả đồng thau vintage 3 bóng cho bàn ăn.',ps:['Đèn thả bàn ăn chất liệu đồng thau (brass) thật 100% — patina tự nhiên theo thời gian tạo vẻ đẹp vintage. 3 bóng E27 LED warm 2700K tạo ánh sáng ấm áp cho bữa ăn gia đình.','Thanh ngang dài 90cm phù hợp bàn ăn 120-180cm. Dây treo điều chỉnh độ cao 50-120cm. Phong cách phù hợp: Mid-Century Modern, Industrial, Scandinavian. Đi kèm 3 bóng LED Edison filament.']},
  {t:'Đèn Sàn Arc Minimalist',c:'Đèn & Phụ kiện',p:6800000,d:'Đèn sàn cần vươn kiểu Arc, chân marble, chao vải linen.',ps:['Đèn sàn Arc lấy cảm hứng từ đèn Arco huyền thoại của Achille Castiglioni. Chân đế marble trắng Carrara thật 8kg giữ vững. Cần thép chrome vươn xa 1.5m — chiếu sáng sofa hoặc góc đọc sách mà không chiếm diện tích sàn.','Chao đèn vải linen tự nhiên tạo ánh sáng khuếch tán mềm mại, không chói. Bóng E27 LED 12W warm. Công tắc foot pedal tiện lợi. Chiều cao tổng thể 2.1m. Đóng gói cẩn thận, giao hàng tận nhà.']},
  {t:'Gương Trang Trí Tròn Khung Gỗ',c:'Đèn & Phụ kiện',p:3200000,d:'Gương tròn đường kính 80cm khung gỗ sồi tự nhiên.',ps:['Gương tròn 80cm — focal point hoàn hảo cho hành lang, phòng khách hoặc phòng tắm. Khung gỗ sồi tự nhiên dày 3cm phủ dầu linseed, giữ vân gỗ tự nhiên. Gương Bỉ 5mm không méo, viền mài bóng.','Có 3 size: 60cm (phòng tắm nhỏ), 80cm (phòng khách/hành lang), 100cm (statement piece). Đi kèm phụ kiện treo tường chịu lực. Tạo cảm giác không gian rộng hơn 30% nhờ phản chiếu ánh sáng.']},
  {t:'Thảm Trải Sàn Jute Tự Nhiên',c:'Đèn & Phụ kiện',p:2500000,d:'Thảm jute 160x230cm dệt thủ công Ấn Độ.',ps:['Thảm jute 100% tự nhiên dệt thủ công từ Ấn Độ — vật liệu bền vững, phân hủy sinh học. Kích thước 160x230cm phù hợp phòng khách 12-20m². Texture braid weave tạo chiều sâu thẩm mỹ cho không gian tối giản.','Màu tự nhiên golden-beige phù hợp mọi phong cách: Scandinavian, Japandi, Boho, Coastal. Chống tĩnh điện, hút ẩm tốt. Lưu ý: không phù hợp khu vực ẩm ướt (phòng tắm, bếp). Vệ sinh bằng máy hút bụi, tránh giặt nước.']},
  {t:'Sofa Đơn Accent Chair Velvet',c:'Sofa & Ghế',p:9800000,d:'Ghế accent bọc velvet cao cấp, chân đồng thau.',ps:['Accent chair velvet là điểm nhấn màu sắc cho phòng khách tối giản. Bọc velvet Ý chống bám bụi, khung gỗ sồi, đệm foam HR mật độ cao 40kg/m³. Chân đồng thau đúc nguyên khối cao 20cm tạo vẻ sang trọng.','5 màu velvet: Emerald Green, Navy Blue, Burnt Orange, Dusty Rose, Charcoal Grey. Kích thước compact 75x80x85cm phù hợp mọi phòng khách. Phong cách: Art Deco, Modern Luxury, Mid-Century Modern. Bảo hành 3 năm.']},
  {t:'Bàn Coffee Gỗ Óc Chó',c:'Bàn & Kệ',p:12800000,d:'Bàn coffee gỗ óc chó tự nhiên mặt epoxy trong suốt.',ps:['Bàn coffee gỗ óc chó (walnut) nguyên tấm — mỗi chiếc là độc bản nhờ vân gỗ tự nhiên khác nhau. Mặt bàn phủ epoxy trong suốt bảo vệ gỗ và tạo hiệu ứng sâu thẳm. Kích thước trung bình 100x60x40cm, nặng khoảng 25kg.','Chân bàn thép sơn tĩnh điện đen matte hoặc đồng thau. Live edge (cạnh tự nhiên) giữ nguyên vỏ cây tạo nét hoang sơ. Phong cách: Wabi-Sabi, Rustic Modern, Industrial. Mỗi bàn kèm certificate gỗ nguồn gốc hợp pháp.']},
  {t:'Kệ TV Floating Gỗ Sồi',c:'Bàn & Kệ',p:7500000,d:'Kệ TV treo tường gỗ sồi 180cm, ẩn dây gọn gàng.',ps:['Kệ TV floating gắn tường 180x30x25cm — tạo cảm giác nhẹ nhàng, thoáng sàn. Gỗ sồi tự nhiên phủ dầu. Hệ thống ẩn dây phía sau — dây điện, HDMI, internet đều chạy trong ống luồn kín, chỉ lộ 1 dây nguồn duy nhất.','Chịu tải 40kg (TV 65 inch + soundbar). Đi kèm bracket treo tường thép 3mm. Ngăn kéo ẩn mặt dưới đựng remote, tai nghe. Lắp đặt bởi đội ngũ VietNet trong 1 giờ bao gồm luồn dây.']},
  {t:'Tủ Bếp Trên L-Shape',c:'Tủ & Lưu trữ',p:45000000,d:'Hệ tủ bếp trên chữ L gỗ công nghiệp An Cường, phụ kiện Blum.',ps:['Hệ tủ bếp chữ L hoàn chỉnh: tủ trên + tủ dưới + countertop đá thạch anh. Cánh tủ MDF An Cường E1 phủ acrylic bóng hoặc laminate vân gỗ. Phụ kiện Blum Áo: bản lề Clip Top tự đóng êm, ray ngăn kéo Tandembox chịu tải 30kg.','Bao gồm: chậu rửa Inox 304 Blanco, vòi rửa Grohe cảm ứng, rổ chén pull-out, thùng rác phân loại tự mở, kệ gia vị xoay góc (tận dụng góc chết). Thiết kế 3D render trước khi sản xuất, chỉnh sửa không giới hạn.']},
  {t:'Đèn LED Panel Âm Trần 60x60',c:'Đèn & Phụ kiện',p:850000,d:'Panel LED 40W ánh sáng đều, tiết kiệm điện cho văn phòng/nhà ở.',ps:['Đèn LED panel 60x60cm 40W thay thế hoàn hảo cho đèn tuýp truyền thống. Ánh sáng khuếch tán đều nhờ tấm LGP (Light Guide Panel) — không bóng đèn, không chói mắt. CRI>90 hiển thị màu sắc chính xác.','3 nhiệt độ màu: 3000K (warm, phòng ngủ), 4000K (natural, phòng khách), 6500K (cool, văn phòng). Tiết kiệm 60% điện so với đèn tuýp. Tuổi thọ 50.000 giờ (11 năm nếu dùng 12h/ngày). Bảo hành 3 năm đổi mới.']},
  {t:'Rèm Linen Blackout 2 Lớp',c:'Đèn & Phụ kiện',p:1800000,d:'Rèm 2 lớp: voan lọc sáng + linen blackout cản 95% ánh sáng.',ps:['Hệ rèm 2 lớp giải quyết mọi nhu cầu: lớp voan trong lọc sáng nhẹ ban ngày, lớp linen blackout cản 95% ánh sáng ban đêm. Giá tính cho cửa 2m rộng x 2.5m cao, bao gồm ray và lắp đặt.','Vải linen polyester blend — vẻ đẹp tự nhiên của linen nhưng bền hơn, không nhăn, giặt máy được. 8 màu: White, Ivory, Oat, Sand, Silver Grey, Sage, Charcoal, Navy. Ray nhôm silent rail Somfy — kéo rèm không tiếng ồn.']},
  {t:'Bàn Làm Việc Standing Desk',c:'Bàn & Kệ',p:8900000,d:'Bàn đứng-ngồi điện điều chỉnh độ cao 65-125cm.',ps:['Standing desk điện motor đôi — điều chỉnh độ cao 65-125cm bằng nút bấm, lưu 4 vị trí yêu thích. Mặt bàn gỗ tre (bamboo) 140x70cm thân thiện môi trường, chịu lực tốt, chống cong vênh. Khung thép chịu tải 80kg.','Tốc độ nâng 3.5cm/giây, tiếng ồn <45dB (yên lặng hơn tủ lạnh). Có khay đựng dây cable management, hook treo tai nghe, và USB-A/C charger tích hợp. Bảo hành motor 5 năm, mặt bàn 3 năm.']},
  {t:'Gối Tựa Lưng Ergonomic',c:'Sofa & Ghế',p:890000,d:'Gối tựa lưng memory foam hỗ trợ cột sống.',ps:['Gối tựa lưng ergonomic với lõi memory foam mật độ cao — ôm sát đường cong cột sống thắt lưng, giảm đau lưng khi ngồi lâu. Vỏ bọc mesh thoáng khí có khóa kéo giặt được. Dây đai elasticcố định vào ghế.','Phù hợp mọi ghế: ghế văn phòng, ghế oto, sofa. Kích thước 35x32x12cm. Màu: đen, xám, beige. Quà tặng lý tưởng cho dân văn phòng. Mua combo 2 cái giảm 15%. Bảo hành 1 năm đổi mới.']},
  {t:'Hộp Đựng Tissue Gỗ Óc Chó',c:'Đèn & Phụ kiện',p:450000,d:'Hộp tissue gỗ óc chó nguyên khối, handmade.',ps:['Hộp tissue gỗ óc chó nguyên khối đục CNC và hoàn thiện thủ công bởi nghệ nhân VietNet. Kích thước 25x13x9cm vừa hộp tissue tiêu chuẩn. Phủ dầu tung oil tự nhiên food-safe, không hóa chất.','Mỗi hộp có vân gỗ tự nhiên khác nhau — sản phẩm độc bản. Đáy có miếng đệm silicone chống trượt. Phù hợp đặt bàn khách, bàn làm việc, đầu giường. Quà tặng premium cho đối tác doanh nghiệp. Set 3 hộp giảm 20%.']},
];

// ─── MAIN ─────────────────────────────────────────────

async function main() {
  // 1. Login
  console.log('Logging in...');
  const loginRes = await req('POST', '/auth/login', { email: 'admin@vietnet.local', password: 'Admin@123' });
  if (loginRes.status !== 200 && loginRes.status !== 201) {
    console.error('Login failed:', loginRes.body);
    return;
  }
  TOKEN = loginRes.body.data?.accessToken || loginRes.body.data?.access_token;
  if (!TOKEN) { console.error('No token in response'); return; }
  console.log('Logged in OK');

  // 2. Get categories
  console.log('Loading categories...');
  const catRes = await req('GET', '/categories?limit=100');
  for (const c of catRes.body.data || []) CATS[c.name] = c.id;
  console.log(`Categories: ${Object.keys(CATS).length}`);

  // 3. Create projects
  console.log('\n--- Creating 20 PROJECTS ---');
  let ok = 0;
  for (let i = 0; i < PROJECTS.length; i++) {
    const p = PROJECTS[i];
    const data = {
      title: p.t, description: p.d, content: mkContent(p.ps),
      category_id: CATS[p.c], style: p.s, area: p.a, location: p.l,
      year_completed: p.y, is_featured: p.f
    };
    const res = await req('POST', '/projects', data);
    if (res.status === 201) {
      await req('PATCH', `/projects/${res.body.data.id}/publish`);
      ok++;
      process.stdout.write(`  [${ok}] ${p.t.substring(0,40)}\n`);
    } else {
      console.error(`  FAIL ${p.t}: ${res.body.message}`);
    }
  }
  console.log(`Projects: ${ok}/20`);

  // 4. Create articles
  console.log('\n--- Creating 20 ARTICLES ---');
  ok = 0;
  for (let i = 0; i < ARTICLES.length; i++) {
    const a = ARTICLES[i];
    const data = {
      title: a.t, excerpt: a.d, content: mkContent(a.ps),
      category_id: CATS[a.c], is_featured: a.f
    };
    const res = await req('POST', '/articles', data);
    if (res.status === 201) {
      await req('PATCH', `/articles/${res.body.data.id}/publish`);
      ok++;
      process.stdout.write(`  [${ok}] ${a.t.substring(0,40)}\n`);
    } else {
      console.error(`  FAIL ${a.t}: ${res.body.message}`);
    }
  }
  console.log(`Articles: ${ok}/20`);

  // 5. Create products
  console.log('\n--- Creating 20 PRODUCTS ---');
  ok = 0;
  for (let i = 0; i < PRODUCTS.length; i++) {
    const p = PRODUCTS[i];
    const data = {
      name: p.t, description: mkContent(p.ps),
      category_id: CATS[p.c], price: p.p, is_featured: i < 6
    };
    const res = await req('POST', '/products', data);
    if (res.status === 201) {
      await req('PATCH', `/products/${res.body.data.id}/publish`);
      ok++;
      process.stdout.write(`  [${ok}] ${p.t.substring(0,40)}\n`);
    } else {
      console.error(`  FAIL ${p.t}: ${res.body.message}`);
    }
  }
  console.log(`Products: ${ok}/20`);

  console.log('\n=== SEED COMPLETE ===');
}

main().catch(console.error);
